import type { Metadata } from "next";
import { Geist, Geist_Mono, Lato, MedievalSharp } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import { AuthProvider } from "./providers/AuthProvider";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const medievalSharp = MedievalSharp({
  variable: "--font-MedievalSharp",
  subsets: ["latin"],
  weight: "400"

});
const lato = Lato({
  variable: "--font-Lato",
  subsets: ["latin"],
  weight: "400"

});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${medievalSharp.variable} antialiased`}
      >
        <AuthProvider>{
          children}
          <NavBar />
        </AuthProvider>
        <ToastContainer position="bottom-left" autoClose={3000} />
      </body>
    </html>
  );
}
